apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2026-08-29T08:51:52Z"
  name: michelle-storage-admin
  resourceVersion: "1531"
  uid: 2a0585e3-d091-4122-9f5c-3290ecd860d8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: michelle