#Create a Pod called redis-storage with image: redis:alpine with a Volume of type emptyDir that lasts for the life of the Pod.
#Specs on the below. Pod named 'redis-storage' created. Pod 'redis-storage' uses Volume type of emptyDir. Pod 'redis-storage' uses volumeMount with mountPath = /data/redis
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-storage
  name: redis-storage
spec:
  containers:
  - image: redis:alpine
    name: redis-storage
    volumeMounts:
    - mountPath: /data/redis
      name: cache-volume
    resources: {}
  volumes:
  - name: cache-volume
    emptyDir:
      #sizeLimit: 500Midd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}