##Create a new pod called super-user-pod with image busybox:1.28. Allow the pod to be able to set system_time.
#The container should sleep for 4800 seconds. Pod: super-user-pod. Container Image: busybox:1.28. Is SYS_TIME capability set for the container?
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: super-user-pod
  name: super-user-pod
spec:
  containers:
  - args:
    - sleep
    - "4800"
    image: busybox:1.28
    name: super-user-pod
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}