apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-25T14:49:13Z"
  name: webapp
  namespace: default
  resourceVersion: "1358"
  uid: 70d39776-b42d-4e9e-9419-db1c5bec6780
spec:
  containers:
  - env:
    - name: LOG_HANDLERS
      value: file
    image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: event-simulator
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /log
      name: webapp-log
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kplsv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/log/webapp
      type: ""
    name: webapp-log
  - name: kube-api-access-kplsv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-12-25T14:49:14Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-12-25T14:49:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-12-25T14:49:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-12-25T14:49:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-12-25T14:49:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0c48c15ae838872c846428741bf724deb34a100ae486caef3607a7ad02716bce
    image: docker.io/kodekloud/event-simulator:latest
    imageID: docker.io/kodekloud/event-simulator@sha256:1e3e9c72136bbc76c96dd98f29c04f298c3ae241c7d44e2bf70bcc209b030bf9
    lastState: {}
    name: event-simulator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-12-25T14:49:14Z"
    volumeMounts:
    - mountPath: /log
      name: webapp-log
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kplsv
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.227.92
  hostIPs:
  - ip: 192.168.227.92
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2024-12-25T14:49:13Z"