apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-19T09:44:34Z"
  generation: 1
  name: elephant
  namespace: default
  resourceVersion: "1265"
  uid: 93f39a33-09d1-4712-82cc-8ede0e13f16b
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7gptg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7gptg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-19T09:44:36Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-19T09:44:34Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-19T09:45:13Z"
    message: 'containers with unready status: [mem-stress]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-19T09:45:13Z"
    message: 'containers with unready status: [mem-stress]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-19T09:44:34Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      memory: 5Mi
    containerID: containerd://9a64afd891474a313344361b08278e8ec254c09d92119d4299d514d926c99360
    image: docker.io/polinux/stress:latest
    imageID: docker.io/polinux/stress@sha256:b6144f84f9c15dac80deb48d3a646b55c7043ab1d83ea0a697c09097aaad21aa
    lastState:
      terminated:
        containerID: containerd://9a64afd891474a313344361b08278e8ec254c09d92119d4299d514d926c99360
        exitCode: 137
        finishedAt: "2026-04-19T09:50:13Z"
        reason: OOMKilled
        startedAt: "2026-04-19T09:50:13Z"
    name: mem-stress
    ready: false
    resources:
      limits:
        memory: 10Mi
      requests:
        memory: 5Mi
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=mem-stress pod=elephant_default(93f39a33-09d1-4712-82cc-8ede0e13f16b)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7gptg
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.25.245
  hostIPs:
  - ip: 192.168.25.245
  observedGeneration: 1
  phase: Running
  podIP: 10.22.0.10
  podIPs:
  - ip: 10.22.0.10
  qosClass: Burstable
  startTime: "2026-04-19T09:44:34Z"