# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-01-14T09:03:01Z"
  name: mysql-service
  namespace: alpha
  resourceVersion: "738"
  uid: e2347056-07df-4841-bfd2-3ff889a1c7be
spec:
  clusterIP: 10.43.75.102
  clusterIPs:
  - 10.43.75.102
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}