apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-01-14T09:07:34Z"
  name: mysql-service
  namespace: beta
  resourceVersion: "1198"
  uid: 8211a962-0a68-4d84-80b1-6b97bb186342
spec:
  clusterIP: 10.43.37.76
  clusterIPs:
  - 10.43.37.76
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}