apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-29T07:56:57Z"
  generation: 1
  labels:
    name: simple-webapp
  name: simple-webapp-1
  namespace: default
  resourceVersion: "3679"
  uid: 385e8d46-d855-4327-9faf-f5e41062943e
spec:
  containers:
  - image: kodekloud/webapp-delayed-start
    imagePullPolicy: Always
    name: simple-webapp
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bkq24
      readOnly: true
    livenessProbe:
      initialDelaySeconds: 80
      periodSeconds: 1
      httpGet:
        path: /live
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-bkq24
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-29T07:57:01Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-29T07:56:57Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-29T08:22:36Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-29T08:22:36Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-29T07:56:57Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://193ef6e7aef959374276ec301e60d62bfed05feaf2e4656a69d365ba2ac25e7a
    image: docker.io/kodekloud/webapp-delayed-start:latest
    imageID: docker.io/kodekloud/webapp-delayed-start@sha256:666b95c2ef8e00a74fa0ea96def8d9d69104ec5d9b9b0f49d8a76bd4c94ad343
    lastState:
      terminated:
        containerID: containerd://e92c0934e5ffdd22c4d176187cac8f555cf086d11adc20d4b1606a5dcb77ed92
        exitCode: 0
        finishedAt: "2026-04-29T08:22:35Z"
        reason: Completed
        startedAt: "2026-04-29T07:57:00Z"
    name: simple-webapp
    ready: true
    resources: {}
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2026-04-29T08:22:36Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bkq24
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.198.210
  hostIPs:
  - ip: 192.168.198.210
  observedGeneration: 1
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2026-04-29T07:56:57Z"